first try to resolve issue #157
rugk/offline-qr-code pull request #257
Opened 2020-09-10 16:08 UTC by schmelto

first try to resolve issue #157

2020-09-11 15:16 UTC, rugk requested changes
Hi @schmelto,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

This is a start, but surely does not work yet. Or did you check the button and notice any difference?

Here is what needs to be done:
* the settings need to be made translatable (i.e. localize them, we have a module for this), see comment
* you need to define the default value, see comment
* most importantly: you need to read the settings value somewhere ([see this module](https://github.com/TinyWebEx/AddonSettings#getting-settings)) and then add the logic to actually hide or show the context menu entries.

Also, BTW, it may be a good idea to adjust the title of this PR to explain what you did and not only link to the issue number.
You can also (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged by adding some "magic" text to your PR _body_. (Manually linked it now.)

BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

2020-09-11 15:16 UTC, rugk commented on src/options/options.js
> +document.getElementById("popupShowContextMenu").checked = true;
Nope, this is not how we do it in this project. See [this answer](https://github.com/rugk/offline-qr-code/issues/157#issuecomment-508475513) and [this doc](https://github.com/TinyWebEx/AddonSettings#default-values) (also consider to read the whole one). You have to define the default setting in `DefaultSettings.js`.

2020-09-11 15:16 UTC, rugk commented on src/options/options.html
> +							<label data-i18n="__MSG_optionPopupShowContextMenu__" for="popupIconShowContextMenu">Show context menu item for selected text</label>
All `__MSG` things need localisation. (At least the English one if you speak no other language.) See [this answer again](https://github.com/rugk/offline-qr-code/issues/157#issuecomment-508475513) and [this doc](https://github.com/TinyWebEx/Localizer).

2020-09-29 20:01 UTC, rugk commented
@schmelto  Are you still interested in completing this? If not, that's no problem, just add a notice, so I know what the current status of this PR is.

2020-10-01 07:00 UTC, schmelto commented
@rugk sorry I'll give it a try at this weekend

2020-12-04 11:25 UTC, rugk commented
@schmelto  Are you still interested in completing this? If not, that's no problem, just add a notice, so I know what the current status of this PR is.

2021-04-19 15:26 UTC, schmelto commented
Hey @rugk think this is outdated from me and someone else can pick it up :)

2021-04-19 15:26 UTC, closed without merging