Allowed extension to use clipboard content to generate QR code when permission given
rugk/offline-qr-code pull request #337
Opened 2024-10-25 22:07 UTC by BrandonTuTwo2

PR for this issue https://github.com/rugk/offline-qr-code/issues/282. Allows the user to create QR codes from copied text from the clipboard granted they give permission to allow the extension to read from the clipboard and turn the setting on. If the clipboard is empty defaults the current tabs URL

2024-10-25 22:07 UTC, BrandonTuTwo2 commented
Hi @rugk I'm ready for a review whenever your free!

2024-10-26 19:59 UTC, rugk requested changes
First review just showed some superfluous lines.

Thanks a lot!

2024-10-26 19:59 UTC, rugk commented on src/options/modules/CustomOptionTriggers.js
> +
I guess remove the superfluous empty lines.

2024-10-26 19:59 UTC, rugk commented on src/options/modules/CustomOptionTriggers.js
> +
Also the first two lines are not needed here.

2024-10-26 19:59 UTC, rugk commented on src/options/options.html
> +
Also remove that hehe

2024-10-28 20:35 UTC, BrandonTuTwo2 commented
Hi @rugk I fixed the spacing issues and added the missing semicolons let me know if there is anything else!

2024-10-31 12:43 UTC, rugk approved these changes

2024-10-31 12:50 UTC, rugk commented
Tested it and it works, except the permission prompt. When you remove the permission (and toggle the setting), you are not prompted for a new permission hmm:
![grafik](https://github.com/user-attachments/assets/3a3f2727-9360-4c55-b874-647423e45802)

Ah okay, that was just me missing the submodule, i see.

Anyway, there is a translation missing here :upside_down_face: :
![grafik](https://github.com/user-attachments/assets/9aa6e177-8d18-45d6-a343-c1f9468c3833)

2024-10-31 13:06 UTC, rugk commented
Okay that was also partially my bad, sorry, because the lib was not really documented in a good way. Added that now/did that now: https://github.com/TinyWebEx/PermissionRequest/tree/master?tab=readme-ov-file#required-translation

And fixed the issue here.

2024-10-31 13:15 UTC, rugk commented
BTW: Next time, try to avoid doing a pull request from the main/master branch, because you can run into problems when you have a "non-clean" main that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

2024-10-31 15:14 UTC, rugk commented
Okay, fixed a small style issue, where the height would be too much when no permission request was shown below the option. See https://github.com/rugk/offline-qr-code/pull/337/commits/71f0932c3509cf5ffb940f449215303999dd71a0

2024-10-31 15:17 UTC, merged

2024-11-09 15:52 UTC, rugk commented
Next time, FYI you can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_. (Manually did it now.)